# Generated by Django 4.2.8 on 2023-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pumpInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pumpNumber', models.CharField(max_length=20)),
                ('vehicleNumber', models.CharField(max_length=50)),
                ('odometer', models.IntegerField(null=True)),
                ('pumpStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
