# Generated by Django 4.2.8 on 2024-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_vehicle_gallonlimit_alter_vehicle_totalgallon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
