# Generated by Django 4.2.8 on 2023-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_pumpinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpinfo',
            name='vehicleNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
