# Generated by Django 4.2.8 on 2024-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_vehicle_gallonlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='totalGallon',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
